config/routes.rb
Rails.application.routes.draw do
  resources :paymenttypes
  resources :gametypes
  resources :gameinstances
  resources :sessions
  root 'homepages#index'
  resources :customerdata
  resources :homepages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/homepage.rb
class Homepage < ApplicationRecord
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  before_action :set_homepage, only: %i[ show edit update destroy ]

  # GET /homepages or /homepages.json
  def index
    @homepages = Homepage.all
    @gameinstances = Gameinstance.all
  end

  # GET /homepages/1 or /homepages/1.json
  def show
  end

  # GET /homepages/new
  def new
    @homepage = Homepage.new
  end

  # GET /homepages/1/edit
  def edit
  end

  # POST /homepages or /homepages.json
  def create
    @homepage = Homepage.new(homepage_params)

    respond_to do |format|
      if @homepage.save
        format.html { redirect_to @homepage, notice: "Homepage was successfully created." }
        format.json { render :show, status: :created, location: @homepage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @homepage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homepages/1 or /homepages/1.json
  def update
    respond_to do |format|
      if @homepage.update(homepage_params)
        format.html { redirect_to @homepage, notice: "Homepage was successfully updated." }
        format.json { render :show, status: :ok, location: @homepage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @homepage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homepages/1 or /homepages/1.json
  def destroy
    @homepage.destroy
    respond_to do |format|
      format.html { redirect_to homepages_url, notice: "Homepage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homepage
      @homepage = Homepage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def homepage_params
      params.fetch(:homepage, {})
    end
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/views/homepages/_form.html.erb
<%= form_with(model: homepage) do |form| %>
  <% if homepage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(homepage.errors.count, "error") %> prohibited this homepage from being saved:</h2>

      <ul>
        <% homepage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homepages/edit.html.erb
<h1>Editing Homepage</h1>

<%= render 'form', homepage: @homepage %>

<%= link_to 'Show', @homepage %> |
<%= link_to 'Back', homepages_path %>

app/views/homepages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homepages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homepages.each do |homepage| %>
      <tr>
        <td><%= link_to 'Show', homepage %></td>
        <td><%= link_to 'Edit', edit_homepage_path(homepage) %></td>
        <td><%= link_to 'Destroy', homepage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<table>
  <thead>
    <tr>
      <th>Sessionid</th>
      <th>Playername</th>
      <th>Betamount</th>
      <th>Gametype</th>
      <th>Multiplier</th>
      <th>Commission</th>
      <th>Paymentname</th>
      <th>Currentprice</th>
      <th>Crypto</th>
      <th>Cryptoprice</th>
      <th>Outcome</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gameinstances.each do |gameinstance| %>
      <tr>
        <td><%= gameinstance.sessionid %></td>
        <td><%= gameinstance.playername %></td>
        <td><%= gameinstance.betamount %></td>
        <td><%= gameinstance.gametype %></td>
        <td><%= gameinstance.multiplier %></td>
        <td><%= gameinstance.commission %></td>
        <td><%= gameinstance.paymentname %></td>
        <td><%= gameinstance.currentprice %></td>
        <td><%= gameinstance.crypto %></td>
        <td><%= gameinstance.cryptoprice %></td>
        <td><%= gameinstance.outcome %></td>
        <td><%= gameinstance.result %></td>
        <td><%= link_to 'Show', gameinstance %></td>
        <td><%= link_to 'Edit', edit_gameinstance_path(gameinstance) %></td>
        <td><%= link_to 'Destroy', gameinstance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Homepage', new_homepage_path %>

app/views/homepages/new.html.erb
<h1>New Homepage</h1>

<%= render 'form', homepage: @homepage %>

<%= link_to 'Back', homepages_path %>

app/views/homepages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_homepage_path(@homepage) %> |
<%= link_to 'Back', homepages_path %>