config/routes.rb
Rails.application.routes.draw do
  resources :paymenttypes
  resources :gametypes
  resources :gameinstances
  resources :sessions
  root 'homepages#index'
  resources :customerdata
  resources :homepages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/gametypes_controller.rb
class GametypesController < ApplicationController
  before_action :set_gametype, only: %i[ show edit update destroy ]

  # GET /gametypes or /gametypes.json
  def index
    @gametypes = Gametype.all
  end

  # GET /gametypes/1 or /gametypes/1.json
  def show
  end

  # GET /gametypes/new
  def new
    @gametype = Gametype.new
  end

  # GET /gametypes/1/edit
  def edit
  end

  # POST /gametypes or /gametypes.json
  def create
    @gametype = Gametype.new(gametype_params)

    respond_to do |format|
      if @gametype.save
        format.html { redirect_to @gametype, notice: "Gametype was successfully created." }
        format.json { render :show, status: :created, location: @gametype }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gametype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gametypes/1 or /gametypes/1.json
  def update
    respond_to do |format|
      if @gametype.update(gametype_params)
        format.html { redirect_to @gametype, notice: "Gametype was successfully updated." }
        format.json { render :show, status: :ok, location: @gametype }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gametype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gametypes/1 or /gametypes/1.json
  def destroy
    @gametype.destroy
    respond_to do |format|
      format.html { redirect_to gametypes_url, notice: "Gametype was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gametype
      @gametype = Gametype.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gametype_params
      params.require(:gametype).permit(:gametype, :multiplier, :commission)
    end
end

app/helpers/gametypes_helper.rb
module GametypesHelper
end

app/views/gametypes/_form.html.erb
<%= form_with(model: gametype) do |form| %>
  <% if gametype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gametype.errors.count, "error") %> prohibited this gametype from being saved:</h2>

      <ul>
        <% gametype.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :gametype %>
    <%= form.text_field :gametype %>
  </div>

  <div class="field">
    <%= form.label :multiplier %>
    <%= form.number_field :multiplier %>
  </div>

  <div class="field">
    <%= form.label :commission %>
    <%= form.number_field :commission %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gametypes/edit.html.erb
<h1>Editing Gametype</h1>

<%= render 'form', gametype: @gametype %>

<%= link_to 'Show', @gametype %> |
<%= link_to 'Back', gametypes_path %>

app/views/gametypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gametypes</h1>
<%= link_to 'New Gametype', new_gametype_path %>
<table>
  <thead>
    <tr>
      <th>Gametype</th>
      <th>Multiplier</th>
      <th>Commission</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gametypes.each do |gametype| %>
      <tr>
        <td><%= gametype.gametype %></td>
        <td><%= gametype.multiplier %></td>
        <td><%= gametype.commission %></td>
        <td><%= link_to 'Show', gametype %></td>
        <td><%= link_to 'Edit', edit_gametype_path(gametype) %></td>
        <td><%= link_to 'Destroy', gametype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/gametypes/new.html.erb
<h1>New Gametype</h1>

<%= render 'form', gametype: @gametype %>

<%= link_to 'Back', gametypes_path %>

app/views/gametypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gametype:</strong>
  <%= @gametype.gametype %>
</p>

<p>
  <strong>Multiplier:</strong>
  <%= @gametype.multiplier %>
</p>

<p>
  <strong>Commission:</strong>
  <%= @gametype.commission %>
</p>

<%= link_to 'Edit', edit_gametype_path(@gametype) %> |
<%= link_to 'Back', gametypes_path %>