config/routes.rb
Rails.application.routes.draw do
  resources :paymenttypes
  resources :gametypes
  resources :gameinstances
  resources :sessions
  root 'homepages#index'
  resources :customerdata
  resources :homepages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/gameinstance.rb
class Gameinstance < ApplicationRecord
end

app/controllers/gameinstances_controller.rb
class GameinstancesController < ApplicationController
  before_action :set_gameinstance, only: %i[ show edit update destroy ]
  before_action :dataaccess
  def dataaccess
    @gametypes = Gametype.all
    @sessions = Session.all
    @paymenttypes = Paymenttype.all
  end
  # GET /gameinstances or /gameinstances.json
  def index
    @gameinstances = Gameinstance.all
  end

  # GET /gameinstances/1 or /gameinstances/1.json
  def show
  end

  # GET /gameinstances/new
  def new
    @gameinstance = Gameinstance.new
  end

  # GET /gameinstances/1/edit
  def edit
  end

  # POST /gameinstances or /gameinstances.json
  def create
    @gameinstance = Gameinstance.new(gameinstance_params)
    respond_to do |format|
      if @gameinstance.save
        format.html { redirect_to @gameinstance, notice: "Gameinstance was successfully created." }
        format.json { render :show, status: :created, location: @gameinstance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gameinstance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gameinstances/1 or /gameinstances/1.json
  def update
    respond_to do |format|
      if @gameinstance.update(gameinstance_params)
        format.html { redirect_to @gameinstance, notice: "Gameinstance was successfully updated." }
        format.json { render :show, status: :ok, location: @gameinstance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gameinstance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gameinstances/1 or /gameinstances/1.json
  def destroy
    @gametypes = Gametype.all
    @gameinstance.destroy
    respond_to do |format|
      format.html { redirect_to gameinstances_url, notice: "Gameinstance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gameinstance
      @gameinstance = Gameinstance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gameinstance_params
      params.require(:gameinstance).permit(:sessionid, :playername, :betamount, :gametype, :multiplier, :commission, :paymentname, :currentprice, :crypto, :cryptoprice, :outcome, :result)
    end
end

app/helpers/gameinstances_helper.rb
module GameinstancesHelper
end

app/views/gameinstances/_form.html.erb
<%= form_with(model: gameinstance) do |form| %>
  <% if gameinstance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gameinstance.errors.count, "error") %> prohibited this gameinstance from being saved:</h2>

      <ul>
        <% gameinstance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sessionid %>
    <%= form.select :sessionid,@sessions.map{|data| data.sessionid} %>
  </div>

  <div class="field">
    <%= form.label :playername %>
    <%= form.text_field :playername %>
  </div>

  <div class="field">
    <%= form.label :betamount %>
    <%= form.text_field :betamount %>
  </div>

  <div class="field">
    <%= form.label :gametype %>
    <%=form.select :gametype,@gametypes.map {|data| [data.gametype,data.id]}%>
  </div>

  <div class="field">
    <%= form.label :multiplier %>
    <%= form.number_field :multiplier %>
  </div>

  <div class="field">
    <%= form.label :commission %>
    <%= form.number_field :commission %>
  </div>

  <div class="field">
    <%= form.label :paymentname %>
    <%=form.select :paymentname,@paymenttypes.map {|data| [data.paymentname,data.id]}%>
    
  </div>

  <div class="field">
    <%= form.label :currentprice %>
    <%= form.text_field :currentprice %>
  </div>

  <div class="field">
    <%= form.label :crypto %>
    <%= form.check_box :crypto %>
  </div>

  <div class="field">
    <%= form.label :cryptoprice %>
    <%= form.text_field :cryptoprice %>
  </div>

  <div class="field">
    <%= form.label :outcome %>
    <%=form.select :outcome,['true','false'] %>
  </div>

  <div class="field">
    <%= form.label :result %>
    <%= form.text_field :result %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gameinstances/edit.html.erb
<h1>Editing Gameinstance</h1>

<%= render 'form', gameinstance: @gameinstance %>

<%= link_to 'Show', @gameinstance %> |
<%= link_to 'Back', gameinstances_path %>

app/views/gameinstances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gameinstances</h1><%= link_to 'New Gameinstance', new_gameinstance_path %>

<table>
  <thead>
    <tr>
      <th>Sessionid</th>
      <th>Playername</th>
      <th>Betamount</th>
      <th>Gametype</th>
      <th>Multiplier</th>
      <th>Commission</th>
      <th>Paymentname</th>
      <th>Currentprice</th>
      <th>Crypto</th>
      <th>Cryptoprice</th>
      <th>Outcome</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gameinstances.each do |gameinstance| %>
      <tr>
        <td><%= gameinstance.sessionid %></td>
        <td><%= gameinstance.playername %></td>
        <td><%= gameinstance.betamount %></td>
        <td><%= gameinstance.gametype %></td>
        <td><%= gameinstance.multiplier %></td>
        <td><%= gameinstance.commission %></td>
        <td><%= gameinstance.paymentname %></td>
        <td><%= gameinstance.currentprice %></td>
        <td><%= gameinstance.crypto %></td>
        <td><%= gameinstance.cryptoprice %></td>
        <td><%= gameinstance.outcome %></td>
        <td><%= gameinstance.result %></td>
        <td><%= link_to 'Show', gameinstance %></td>
        <td><%= link_to 'Edit', edit_gameinstance_path(gameinstance) %></td>
        <td><%= link_to 'Destroy', gameinstance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/gameinstances/new.html.erb
<h1>New Gameinstance</h1>

<%= render 'form', gameinstance: @gameinstance %>

<%= link_to 'Back', gameinstances_path %>

app/views/gameinstances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sessionid:</strong>
  <%= @gameinstance.sessionid %>
</p>

<p>
  <strong>Playername:</strong>
  <%= @gameinstance.playername %>
</p>

<p>
  <strong>Betamount:</strong>
  <%= @gameinstance.betamount %>
</p>

<p>
  <strong>Gametype:</strong>
  <%= @gameinstance.gametype %>
</p>

<p>
  <strong>Multiplier:</strong>
  <%= @gameinstance.multiplier %>
</p>

<p>
  <strong>Commission:</strong>
  <%= @gameinstance.commission %>
</p>

<p>
  <strong>Paymentname:</strong>
  <%= @gameinstance.paymentname %>
</p>

<p>
  <strong>Currentprice:</strong>
  <%= @gameinstance.currentprice %>
</p>

<p>
  <strong>Crypto:</strong>
  <%= @gameinstance.crypto %>
</p>

<p>
  <strong>Cryptoprice:</strong>
  <%= @gameinstance.cryptoprice %>
</p>

<p>
  <strong>Outcome:</strong>
  <%= @gameinstance.outcome %>
</p>

<p>
  <strong>Result:</strong>
  <%= @gameinstance.result %>
</p>

<%= link_to 'Edit', edit_gameinstance_path(@gameinstance) %> |
<%= link_to 'Back', gameinstances_path %>