config/routes.rb
Rails.application.routes.draw do
  resources :paymenttypes
  resources :gametypes
  resources :gameinstances
  resources :sessions
  root 'homepages#index'
  resources :customerdata
  resources :homepages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/paymenttypes_controller.rb
class PaymenttypesController < ApplicationController
  before_action :set_paymenttype, only: %i[ show edit update destroy ]

  # GET /paymenttypes or /paymenttypes.json
  def index
    @paymenttypes = Paymenttype.all
  end

  # GET /paymenttypes/1 or /paymenttypes/1.json
  def show
  end

  # GET /paymenttypes/new
  def new
    @paymenttype = Paymenttype.new
  end

  # GET /paymenttypes/1/edit
  def edit
  end

  # POST /paymenttypes or /paymenttypes.json
  def create
    @paymenttype = Paymenttype.new(paymenttype_params)

    respond_to do |format|
      if @paymenttype.save
        format.html { redirect_to @paymenttype, notice: "Paymenttype was successfully created." }
        format.json { render :show, status: :created, location: @paymenttype }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paymenttype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paymenttypes/1 or /paymenttypes/1.json
  def update
    respond_to do |format|
      if @paymenttype.update(paymenttype_params)
        format.html { redirect_to @paymenttype, notice: "Paymenttype was successfully updated." }
        format.json { render :show, status: :ok, location: @paymenttype }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paymenttype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paymenttypes/1 or /paymenttypes/1.json
  def destroy
    @paymenttype.destroy
    respond_to do |format|
      format.html { redirect_to paymenttypes_url, notice: "Paymenttype was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paymenttype
      @paymenttype = Paymenttype.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paymenttype_params
      params.require(:paymenttype).permit(:paymentname, :currentprice, :crypto, :cryptourl)
    end
end

app/helpers/paymenttypes_helper.rb
module PaymenttypesHelper
end

app/views/paymenttypes/_form.html.erb
<%= form_with(model: paymenttype) do |form| %>
  <% if paymenttype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paymenttype.errors.count, "error") %> prohibited this paymenttype from being saved:</h2>

      <ul>
        <% paymenttype.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :paymentname %>
    <%= form.text_field :paymentname %>
  </div>

  <div class="field">
    <%= form.label :currentprice %>
    <%= form.text_field :currentprice %>
  </div>

  <div class="field">
    <%= form.label :crypto %>
    <%= form.check_box :crypto %>
  </div>

  <div class="field">
    <%= form.label :cryptourl %>
    <%= form.text_field :cryptourl %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/paymenttypes/edit.html.erb
<h1>Editing Paymenttype</h1>

<%= render 'form', paymenttype: @paymenttype %>

<%= link_to 'Show', @paymenttype %> |
<%= link_to 'Back', paymenttypes_path %>

app/views/paymenttypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paymenttypes</h1>
<%= link_to 'New Paymenttype', new_paymenttype_path %>
<table>
  <thead>
    <tr>
      <th>Paymentname</th>
      <th>Currentprice</th>
      <th>Crypto</th>
      <th>Cryptourl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paymenttypes.each do |paymenttype| %>
      <tr>
        <td><%= paymenttype.paymentname %></td>
        <td><%= paymenttype.currentprice %></td>
        <td><%= paymenttype.crypto %></td>
        <td><%= paymenttype.cryptourl %></td>
        <td><%= link_to 'Show', paymenttype %></td>
        <td><%= link_to 'Edit', edit_paymenttype_path(paymenttype) %></td>
        <td><%= link_to 'Destroy', paymenttype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/paymenttypes/new.html.erb
<h1>New Paymenttype</h1>

<%= render 'form', paymenttype: @paymenttype %>

<%= link_to 'Back', paymenttypes_path %>

app/views/paymenttypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Paymentname:</strong>
  <%= @paymenttype.paymentname %>
</p>

<p>
  <strong>Currentprice:</strong>
  <%= @paymenttype.currentprice %>
</p>

<p>
  <strong>Crypto:</strong>
  <%= @paymenttype.crypto %>
</p>

<p>
  <strong>Cryptourl:</strong>
  <%= @paymenttype.cryptourl %>
</p>

<%= link_to 'Edit', edit_paymenttype_path(@paymenttype) %> |
<%= link_to 'Back', paymenttypes_path %>